# Generated by Django 4.1.7 on 2023-03-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('Meeting_id', models.AutoField(primary_key=True)),
                ('Meeting_name', models.CharField(max_length=255)),
                ('Meeting_type', models.CharField(max_length=255)),

                ('Meeting_date', models.DateField()),
                ('Meeting_time', models.TimeField()),
                ('Meeting_duration', models.CharField(max_length=255)),
                ('Meeting_attendees', models.TextField()),
                ('Meeting_notes', models.TextField()),
                ('Meeting_deleted', models.BooleanField()),
                                
                
                
            ],
        ),
    ]
