# Generated by Django 4.1.7 on 2023-04-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='Meeting_attendees',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Meeting_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Meeting_deleted',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Meeting_duration',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Meeting_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Meeting_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Meeting_notes',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Meeting_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Meeting_type',
        ),
        migrations.AddField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
